
[tool.black]
line-length = 79
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | __pycache__
  | docs
  | examples
  | st_dicts
  | train
  | scripts
)/
'''

[tool.isort]
profile = "black"
line_length = 79
known_first_party = ["bot", "CycleGan"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
skip = ["docs", "examples", "st_dicts", "train", "scripts", "__pycache__"]

[tool.flake8]
max-line-length = 79
ignore = "E203, W503, E501"
max-complexity = 15
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "docs",
    "examples",
    "st_dicts",
    "train",
    "scripts"
]
